### ISSUE TITLE
[BUG] Rofi steals Hyprland KB input

### ISSUE THREAD

**Issue by kRHYME7** [lbonn/rofi#119]
### Rofi version (rofi -v or git commit in case of build issue)

1.7.5.wayland2.r213.gb847cb35-1

### Configuration

even without configs https://gist.github.com/kRHYME7/4ed2a3f8a6b2b07a9bc64ef390d077d7

### Theme

even without configs https://gist.github.com/kRHYME7/4ed2a3f8a6b2b07a9bc64ef390d077d7

### Timing report

even without configs https://gist.github.com/kRHYME7/4ed2a3f8a6b2b07a9bc64ef390d077d7

### Launch command

``` rofi ``` 

### Step to reproduce

* Open any rofi layer
* Press hyprland keybind
*  Keybind is ignored

### Expected behavior

Hyprland keybinding can still be executed even the rofi layer is rendered. 

### Actual behavior

I think rofi is prioritized for keyboard input. 

### Additional information

* Downgrading to ``` 1.7.5.wayland2.r211.g2ddef0f8-1 ``` should provide the expected behavior. 

* May I ask if this is a hyprland specific thing? 
* Should we add new/additional configuration for rofi? 

Thanks in advance @lbonn  🙌

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
@kRHYME7 yes that's something I've added yesterday to be able to re-use bindings from rofi.

Sorry, I should have put this behind an option flag. Will do in a bit...

**Comment by kRHYME7** [comment]
If it's possible can we make this new feature arbitrary?(compatibility for older configs)

But any would still be cool.💪

**Comment by lbonn** [comment]
Yes, I will set it opt-in. Given the speed a report came back, it looks like at least a few users prefer the current way :grin:

**Comment by kRHYME7** [comment]
Thank you!

**Comment by Sahil-958** [comment]
Hello @lbonn,

Could you please verify if the following behavior is intentional:

When the Rofi layer is active, it currently intercepts all keystrokes except for the global compositor keybindings. This means that it's impossible to type text in other applications while a Rofi layer is open.

While this isn't a problem in most scenarios, it does create issues in specific cases, such as when I need to take a screenshot of the Rofi window. In such situations, I have to resort to running a script from the terminal and selecting the Rofi window using fzf. However, due to Rofi intercepting normal keyboard input, this workaround isn't feasible.

I'm using Hyprland as my WM.
