### ISSUE TITLE
[BUG] Rofi-lbonn doesn't respect cursor theme & size in sway

### ISSUE THREAD

**Issue by Mel34** [lbonn/rofi#20]
## Version

Output of `rofi -v`
Version: 1.6.1-wayland

## Launch Command

`The commandline used to launch **rofi**`
rofi -modi drun -show drun

## Steps to reproduce

run sway
run rofi-lbonn variant in sway

## What behaviour you see

- mouse cursor changes size when hovered over rofi
- mouse cursor theme also changes

## What behaviour you expect to see

- mouse cursor size remains constant
- mouse cursor theme is correctly applied

**Additional details:**

https://user-images.githubusercontent.com/13254332/105858123-44bb2200-5feb-11eb-837c-4cbc74ca72dc.mp4

**Comment by digital-mystik** [comment]
I forgot what I ended up doing since it was a while back, but was able to change the cursor to something else (might have been with gsettings, editing settings.ini, setting xcursor in sway's config, or something along those lines), but am unable to downsize the cursor size when hovering over the menu even with everything I can think of set to the desired size. Wonder where rofi-lbonn pulls its cursor settings from, did you ever find a fix?

**Comment by aacebedo** [comment]
Same issue here,
The size and theme of the cursor in lboon rofi is not the same as in other apps.
I tried changing the different settings (gsettings, xcursor, settings.ini) without success.
That's the only bug I suffer of between the original xorg rofi version and this one.

**Comment by Sporif** [comment]
The culprit is this [line](https://github.com/lbonn/rofi/blob/97953eddd42eb137174f75dcde88da6d8c7481ea/source/wayland/display.c#L1212). It should be 24 by default and use the env var XCURSOR_SIZE if set.

For example, this is [swaybar's method](https://github.com/swaywm/sway/blob/f4db502d4470f2ed87b63ee4b73d1b98506a715c/swaybar/input.c#L71-L80).

**Comment by lbonn** [comment]
@Sporif great! Thanks for looking into this!

Would you like to open a PR with the fix?
