### ISSUE TITLE
[REQUEST] Create tag for release 1.7.0-wayland

### ISSUE THREAD

**Issue by jirutka** [lbonn/rofi#28]
There’s tag [1.6.1-wayland](https://github.com/lbonn/rofi/tree/1.6.1-wayland), but 1.7.0-wayland is missing. Can you please create it?

**Comment by lbonn** [comment]
It would be nice to merge #26 and have the tarball generated for the tag after it's pushed. I'll try to review it soon and then push the tag.

**Comment by tinywrkb** [comment]
Why? Is this still a WIP fork with the goal of upstreaming or a separate project?  
Do you really think `1.6.1-wayland` is a good name for tagged release? How do you suggest bug fixes releases should be named? `1.7.0-wayland.1`, `1.7.0-wayland.2`...  
If upstreaming is not in the horizon, then maybe rename the upstream tags or remove them completely, and only tag releases with Wayland support.

**Comment by lbonn** [comment]
Upstreaming would be ideal yes but probably won't happen in the current context. The first reason for this fork was for my own usage and making it public helps improving its quality. Now, people have started packaging it so it makes sense to have some kind of releases.

Removing the upstream tags is fine by me but I'd still like to avoid colliding version names with actual rofi versions.

It's still time to change the version scheme though, I am open to suggestions.
`1.6.1.w0`, `1.6.1.w1`..?

**Comment by tinywrkb** [comment]
> It's still time to change the version scheme though, I am open to suggestions.
1.6.1.w0, 1.6.1.w1..?

Sounds fine to me.

**Comment by jirutka** [comment]
> It's still time to change the version scheme though, I am open to suggestions.
> 1.6.1.w0, 1.6.1.w1..?

This is quite unusual versioning scheme. What about just adding fourth digit – 1.6.1.0, 1.6.1.1?

**Comment by jirutka** [comment]
It’d be also better to rename this repository to `rofi-wayland`.

**Comment by lbonn** [comment]
Renaming the repository can cause problems and confusion, I would prefer not too. Probably github proposes a redirection after the rename but still...

For the versioning, there is probably no perfect pretty solution. This program is still a fork and we intend to continue merging back the changes from upstream rofi. Basically, the two repository can live as remotes of the same git checkout without issues and the release names should be easily distinguishable from rofi releases.

Another example is the linux kernel with its multiple forks. Let's look at linux-rt:

https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/
https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/refs/?h=linux-5.4.y-rt

So for each base linux version, they start with 5.x-rt1, then 5.x.1-rt2 , 5.x.2-rc1-rt3 (this one is a bit weird but we probably won't have that problem here).

The next release name could be:

* 1.7.0.w1
* 1.7.0-w1
* 1.7.0-wayland1

After second thoughts, the `-` in the name makes a bit more sense. 1.7.0-wayland1 is quite long but is more consistent with 1.6.1-wayland already release (minor point).

1.7.0-w1 is the less offending IMO. I will release it next if there are not strong objections.

**Comment by tinywrkb** [comment]
I'm o.k. with any of the suggestions.  
In Arch Linux, we always replace the hyphens with dots in the project release version, so the choice of hyphen or dot doesn't matter in regard to Arch Linux packaging.  
Hyphen is the delimiter between the project version and the packaging version (changes only in packaging), so the version of an Arch Linux package is `project_version-packaging_version`.

**Comment by jirutka** [comment]
> Renaming the repository can cause problems and confusion, I would prefer not too.

I’d say that the current name cause problems – pretty bad discoverability (it’s hard to find) and ambiguity when referring this project and naming packages.

>1.7.0.w1
>1.7.0-w1
>1.7.0-wayland1

I’d prefer the last one, it’s at least clear. `w1` is very confusing, it’s not clear what’s the meaning of `w` and that it’s a static part.

> 1.7.0-w1 is the less offending IMO.

Please note that package versioning scheme in Alpine Linux, Gentoo and probably a few more distros doesn’t allow hyphens in a version number (pkgver). For this reason, I’ll have to convert it for the `pkgver` into a different format, probably 1.7.0.1 or 1.7.0_p1. It’s not a problem, I’m writing it just FYI.

**Comment by lbonn** [comment]
Ok thanks for your feedback. Still, something else than a `.` seems appropriate to separate the two parts of the version.

New favorite options: `1.7.0+wayland1` or `1.7.0+wayland.1`

**Comment by tinywrkb** [comment]
> New favorite options: 1.7.0+wayland1 or 1.7.0+wayland.1

No objection here.

**Comment by lbonn** [comment]
https://github.com/lbonn/rofi/releases/tag/1.7.0%2Bwayland1

**Comment by jirutka** [comment]
`1.7.0+wayland.1` would be better than `1.7.0+wayland1`.
